ChatApp.PresentationLayer/Controllers/UserController.cs
using ChatApp.BusinessLogicLayer.Abstract;
using ChatApp.BusinessLogicLayer.DTOs;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using MailKit.Net.Smtp;
using ChatApp.BusinessLogicLayer.Validators;
using FluentValidation;
using Microsoft.AspNetCore.Identity;
using ChatApp.EntitiesLayer.Model;
using ChatApp.BusinessLogicLayer.Concrete;



namespace ChatApp.PresentationLayer.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IValidator<UserUpdateInformationDTO> _validator;
        private readonly UserManager<AppUser> _userManager;
       
        
        public UserController(UserManager<AppUser> userManager,IUserService userService,IValidator<UserUpdateInformationDTO> validator) { 
        
            _userService = userService;
            _validator = validator;
            _userManager = userManager;
            
        
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.SidebarSize = "Small";


            var user = await _userService.GetHostUser();

            UserUpdateInformationDTO userInformationDTO = new UserUpdateInformationDTO()
            {

                Email = user.Email,
                Nickname = user.Nickname,
                UserName = user.UserName


            };

            return View(userInformationDTO);
        }

        [HttpPost]
        public  async Task<IActionResult> Index(UserUpdateInformationDTO userInformationDTO)
        {
            ViewBag.SidebarSize = "Small";

            var user = await _userService.GetHostUser();

            var result = _validator.Validate(userInformationDTO);

           
                foreach (var error in result.Errors)
                {

                    ModelState.AddModelError(String.Empty, error.ErrorMessage);
                    
                }
            
                if(!ModelState.IsValid)
                {

                return View();

                }

         
            user.UserName = userInformationDTO.UserName != null ? userInformationDTO.UserName : user.UserName;
            
            user.Nickname = userInformationDTO.Nickname != null ? userInformationDTO.Nickname : user.Nickname;
            user.SecurityStamp = Guid.NewGuid().ToString();

           
                
                await _userManager.UpdateAsync(user);
            
        if(userInformationDTO.Email != null)
            {
                TempData["NewEmail"] = userInformationDTO.Email;

                return RedirectToAction("Email", "EmailVerification");
            }
          



            return View(userInformationDTO);
        }

        public  IActionResult ChangePassword()
        {
			ViewBag.SidebarSize = "Small";


			return View();
        }

        [HttpPost]


        public IActionResult ChangePassword(UserUpdateInformationDTO userInformationDTO)
        {
            ViewBag.SidebarSize = "Small";

            var result = _validator.Validate(userInformationDTO);

            foreach(var error in result.Errors)
            {
                ModelState.AddModelError(String.Empty,error.ErrorMessage);
            }

            if(!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                if(userInformationDTO.Password != null)
                {
                    TempData["NewPassword"] = userInformationDTO.Password;
                    TempData["CurrentPassword"] = userInformationDTO.CurrentPassword;


                    return RedirectToAction("Password", "EmailVerification");
                }
            }


            return View();
        }

       


    }
}

ChatApp.PresentationLayer/Views/ViewComponents/ResultMessagesViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ChatApp.PresentationLayer.Views.ViewComponents
{
    public class ResultMessagesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {



            return View();
        }
    }
}

ChatApp.PresentationLayer/Views/ViewComponents/ScriptsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ChatApp.PresentationLayer.Views.ViewComponents
{
    public class ScriptsViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke()
        {



            return View();
        }
    }
}

ChatApp.PresentationLayer/Views/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ChatApp.PresentationLayer.Views.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke()
        {


            return View();

        }
    }
}

ChatApp.PresentationLayer/Views/User/ChangePassword.cshtml
@model UserUpdateInformationDTO
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="~/login-form/style.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/chat.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    @await Component.InvokeAsync("Sidebar")

    <input type="checkbox" id="flip">
    <div class="forms">
        <div class="form-content">
            <div class="signup-form">
                <div class="title">My Account</div>
                <form method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="All" style="color:red;"></div>
                    <div class="row input-boxes">
                        <div class="input-box col-6">
                            <i class="fa-solid fa-lock"></i>
                            <input type="text" name="CurrentPassword" placeholder="Current Password">
                        </div>
                        <div class="input-box col-6">
                            <i class="fa-solid fa-lock"></i>
                            <input type="text" name="Password" placeholder="New Password">
                        </div>

                        <div class="input-box">
                            <i class="fa-solid fa-lock"></i>
                            <input type="text" name="ConfirmPassword" placeholder="Confirm Password">
                        </div>


                       




                        <div class="button input-box">
                            <input type="submit" value="Update">
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>

    
    @await Component.InvokeAsync("Scripts")

    @await Component.InvokeAsync("ResultMessages")
</body>





</html>

ChatApp.PresentationLayer/Views/User/Index.cshtml
@model UserUpdateInformationDTO
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="~/login-form/style.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/chat.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    @await Component.InvokeAsync("Sidebar")
    
        <input type="checkbox" id="flip">
        <div class="forms">
            <div class="form-content">
                <div class="signup-form">
                    <div class="title">My Account</div>
                    <form method="post" enctype="multipart/form-data">
                        <div asp-validation-summary="All" style="color:red;"></div>
                        <div class="row input-boxes">
                            <div class="input-box col-6">
                                <i class="fas fa-user"></i>
                                <input type="text"  name="UserName">
                            </div>
                            <div class="input-box col-6">
                                <i class="fas fa-signature"></i>
                                <input type="text"  name="Nickname">
                            </div>

                            <div class="input-box">
                                <i class="fas fa-envelope"></i>
                                <input type="text"  name="Email" >
                            </div>


                            <input class="form-control" id="UserImage" asp-for="UserImage">




                            <div class="button input-box">
                                <input type="submit" value="Update">
                            </div>
                            
                        </div>
                    </form>
                </div>
            </div>
        </div>
 
    @await Component.InvokeAsync("Scripts")

    @await Component.InvokeAsync("ResultMessages")
   
</body>



    

</html>